### ISSUE TITLE
Game Loop: Part 1

### ISSUE THREAD

**Issue by jduong09** [jduong09/thirteen#12]
## Feature Overview

- Feature to simulate first player turn and subsequent players turns until turn cycle is complete

### ToDo

-  [x] Functionality to start from turn 1 and prompt player 1 to play cards (DANIEL)
-  [x] Game validating what they played (JUSTIN)
-  [x] Game removing the played cards from their hand, and setting the turns combination. (DANIEL)
-  [x] Moving to player 2, and prompting them to play cards that fit the combination (DANIEL)
-  [x] Validating player 2s choice for valid combo and higher value. (JUSTIN)
-  [ ] Pass removing user from current turns cycle. (JUSTIN)
-  [x] Change numbers array so values 3-15 are not strings, but numbers (JUSTIN)

**Comment by jduong09** [comment]
## Future Issue

- If a combo is played and all subsequent players pass their turn, current turns combination needs to be reset to null and a new turn cycle would begin.
