### ISSUE TITLE
Game Component

### ISSUE THREAD

**Issue by ziggysauce** [jduong09/thirteen#5]
## Part 1

- [x] Deck of cards (array of 52 cards)
  - Array of 52 cards
- [x] Shuffle the deck of cards
  - Random sort
- [x] Distribute random cards to 4 users
  - Separate into 4 arrays of 13 "card" objects
  - `{number: <number>, suite: <suit>}`
- [x] Assign first player (3 of spades)

BONUS
- [x] Implement SASS/SCSS
## Part 2

- [x] Tracker (to determine whose turn it is) [DAN]
- [x] Validate each player's turn submission [DAN]
  - [x] If turn is valid, accept cards and move on to next player
  - [x] If turn is invalid, send error message to player
- [x] Pass functionality [DAN]
- [x] Determine if no play can be made [SEPARATE INTO SEVERAL TICKETS]

**Comment by ziggysauce** [comment]
Updates:
- Add function for accepting a combo array (a hand) and pass that down to the hand component

**Comment by jduong09** [comment]
Closing.
